apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: eureka-server-deployment
spec:
  selector:
    matchLabels:
      app: eureka-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: eureka-app
    spec:
      containers:
        - name: eureka-app-container
          image: dali05/eureka-server-img # Image that will be used to containers in the cluster